version: '3'
services:

  ## Database

  todo-db:
    image: postgres
    container_name: todo-db
    volumes:
      - ./config/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: tododb
    ports:
      - 5432:5432

  ## App

  todo-app:
    image: well5a/todolist
    container_name: todo-app
    depends_on:
      - todo-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://todo-db:5432/tododb
      SPRING_DATASOURCE_USERNAME: todo
      SPRING_DATASOURCE_PASSWORD: todo
    entrypoint: ["sh", "-c", "java -jar /app.jar"]
    ports:
      - 5555:5555

